{{ if .Values.config.enableLeaderElection }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kro:controller:leader-election
  namespace: "{{ .Release.Namespace }}"
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kro:controller:leader-election
  namespace: "{{ .Release.Namespace }}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kro:controller:leader-election
subjects:
  - kind: ServiceAccount
    name: { { include "kro.serviceAccountName" . } }
    namespace: "{{ .Release.Namespace }}"
{{ end }}
